---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
    - ospf
  connection: local
  gather_facts: no

  vars:
   config_assemble: "{{ user_data_path }}/config/{{ inventory_hostname }}" 
   config_assemble_build: "{{ config_assemble }}/build" 
   config_file: "{{ config_assemble }}/ospf.conf" 
   playbook_name: ospf-settings.yaml 

  pre_tasks:
    - name: confirm or create device config directory
      file:
        path: "{{ config_assemble}}"
        state: directory

    - name: delete previous build directory
      file:
        path: "{{ config_assemble_build}}"
        state: absent

    - name: create build directory
      file:
        path: "{{ config_assemble_build}}"
        state: directory


  tasks:
    - name: assemble config fragments
      assemble:
        src: "{{ config_assemble_build }}"
        dest: "{{ config_file }}"
      notify: install config onto device   

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: yes

  handlers:
    - name: install config onto device
      juniper_junos_config:
        provider:
           host: "{{ ansible_host }}"
           user: "{{ username }}"
           passwd: "{{ password }}"
           port: 22
           timeout: 120
        src: "{{ config_file }}"
        load: merge
        comment: "playbook ospf-settings.yaml"
