---
- name: Prepare for configuration build
  hosts: localhost
  tasks:
  - shell: |
      mkdir -p {{config_dir}}
      rm -fr {{build_dir}}
      mkdir -p {{build_dir}}
      cd {{build_dir}}
      mkdir {{groups['all']|join(' ')}}
    args:
      warn: false
    changed_when: false

- name: Generate configs
  hosts: all
  connection: local
  roles:
    - base
